### PR TITLE
[PRED-2278] Use unicode when logging a debug info with response.

### PR DESCRIPTION
**Pull request by kleschenko**
# BATCH SCORING PULL REQUEST

This is a pull request into a **public** repository for Batch Scoring script maintained by DataRobot.

## CHANGES
- Use unicode strings when formatting a response text.

### CODE REVIEW

**Comment by kleschenko** [comment]
@datarobot/predictions can someone merge this PR and build a new library package?

**Comment by farafarafara** [comment]
@kleschenko will merge, not sure we want to release a new package, @ikalnytskyi what do you think in this regards? Was this bug breaking many requests?

**Comment by ikalnytskyi** [comment]
@farafarafara from what I can say, it only crashes if (a) you send a unicode data and (b) predictions for those unicode data failed (e.g. missing column).

**Comment by farafarafara** [comment]
@ikalnytskyi do you think it is necessary to release a new batch scoring version now?

**Pull request merged**
