### PR TITLE
Error messaging for incorrect encoding when using fast_mode [PRED-1095]

### PR DESCRIPTION
**Pull request by brianpendleton**
Example of the new error message in action.
```
MainProcess [ERROR] 'ascii' codec can't decode byte 0xc2 in position 348134: ordinal not in range(128)
MainProcess [ERROR] You are using --fast option, which uses a small sample of data to figuring out the encoding of your file. You can try to specify the encoding directly for this file by using the encoding flag (e.g. --encoding utf-8). You could also try to remove the --fast mode to auto-detect the encoding with a larger sample
```

### CODE REVIEW

**Comment by dsakagi** [comment]
The tests are hanging - was this an issue before my recent pull request, or is mine the most likely culprit?

**Comment by brianpendleton** [comment]
Can I bump these tests using Jarvis?

**Comment by brianpendleton** [comment]
@dsakagi the flakes are gone.  Does this look good to you?

**Comment by dsakagi** [comment]
If you are authenticated with Travis, you can see a "Rerun job" button for future flakes.

**Comment by dsakagi** [comment]
:shipit:

**Pull request merged**
