### PR TITLE
[MMSQUAD-2778] batch-scoring tests for multi class data

### PR DESCRIPTION
**Pull request by vikua**
### Jira 
[MMSQUAD-2778](https://datarobot.atlassian.net/browse/MMSQUAD-2778) 

### Description
Tests for multi class case in batch-scoring.

### CODE REVIEW

**Comment by brianbelljr** [comment]
jarvis please test continuous-integration/travis-ci/push

**Comment by sevikkk** [comment]
Is it supposed to work or it's WIP?
Tests are failing with obvious difference in results...

**Comment by vikua** [comment]
@sevikkk, this test is passing locally so yeah, it is supposed to work. 
Let me figure why it is failing here

**Comment by vikua** [comment]
oops, my mistake

**Pull request merged**
