### PR TITLE
Do not hang on CSV parse error (PRED-922)

### PR DESCRIPTION
**Pull request by sevikkk**

### CODE REVIEW

**Comment by Axik** [comment]
Minor nitpick: do we need to have 1k+ lines fixtures for this?

**Comment by sevikkk** [comment]
we need a big fixture to pass initial check by investigate_encoding_and_dialect

**Comment by Axik** [comment]
Can you also add bugfix description to CHANGES?

**Comment by sevikkk** [comment]
If I add changes to CHANGES - it will conflict with 908.. gr

**Comment by sevikkk** [comment]
I'll add all of them to CHANGES in separate PR

**Pull request merged**
