### PR TITLE
see if windows tests pass now

### PR DESCRIPTION
**Pull request by mckaymatt**

### CODE REVIEW

**Comment by mckaymatt** [comment]
We were skipping some tests because they would fail on Windows with Python3.5 in Appveyor. I suspected that executor.map was causing the problems and wanted to see if they would pass now... and it looks like they do. We could fully test Windows now.

The only real issue is that the Windows tests on Appveyor take forever. 

Thoughts? @sevikkk @Axik

**Comment by sevikkk** [comment]
Looks like Appveyor is especially slow on tests with big fixtures like regression_jp and regression_bad. But files are just 200k...

**Comment by sevikkk** [comment]
With changes to n_samples tests run much faster

**Comment by mckaymatt** [comment]
Oh wow, that's a huge improvement. I'm comfortable merging this.

**Comment by sevikkk** [comment]
I'm comfortable too, it's your PR :)

**Comment by mckaymatt** [comment]
Oh I need to update the docs

**Pull request merged**
